-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "calle" DROP NOT NULL,
ALTER COLUMN "numero_direccion" DROP NOT NULL,
ALTER COLUMN "ciudad" DROP NOT NULL,
ALTER COLUMN "cod_postal" DROP NOT NULL,
ALTER COLUMN "pais" DROP NOT NULL,
ALTER COLUMN "telefono" DROP NOT NULL,
ALTER COLUMN "rol" SET DEFAULT 'Cliente';
