services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=antonio
      - POSTGRES_DB=PreseHome
    networks:
      - presehome_red

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "80:80"
    networks:
      - presehome_red

networks:
  presehome_red:
    driver: bridge

volumes:
  psql:
