FROM node:23

WORKDIR /app
COPY . .

COPY package*.json ./
RUN npm install

ENV DATABASE_URL="postgresql://antonio:password@db:5432/PreseHome"
ENV EMAIL_USER=toni2002gr@gmail.com
ENV EMAIL_PASS='zbjv dktn rbla hzti'
ENV RECIPIENT_EMAIL=antoniordr02@gmail.com
ENV JWT_SECRET=miClaveSecretaSuperSegura
ENV COOKIE_SECRET=miClaveSecretaSuperSegura
ENV GOOGLE_CLIENT_ID=281192872665-7vq3o56p5dsr72mgj8qgoj5m10g68pfq.apps.googleusercontent.com
ENV GOOGLE_CLIENT_SECRET=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
ENV IN=production

RUN npx prisma generate

EXPOSE 5000

CMD ["sh", "-c", "npx prisma migrate deploy && node src/server.js"]